export enum HttpError {
    UNAUTHORIZED,
    NOT_VALID_SLUG,
    NOT_VALID_AMOUNT,
    NOT_VALID_PRICE,
    NOT_VALID_EXPIRATION,
    NO_COLLECTION_FOUND,
    NOT_VALID_PRE_MESSAGE,
    NOT_VALID_NONCE,
    NOT_NFT_HOLDER,
    LOGIN_ERROR,

    INTERNAL_SERVER_RROR,
}